create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.languages (
  id text primary key,
  display_name text not null,
  file_extension text not null,
  comment_syntax text not null,
  execution_runtime text not null,
  compiled boolean not null default false,
  tier smallint not null check (tier in (1, 2, 3)),
  sort_order integer not null default 0,
  supports_stdin boolean not null default true,
  supports_packages boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  human_language text not null default 'en',
  preferred_programming_language_id text references public.languages(id) on delete set null,
  xp integer not null default 0,
  streak integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.topics (
  id text primary key,
  title text not null,
  description text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  language_id text not null references public.languages(id) on delete cascade,
  topic_id text not null references public.topics(id) on delete cascade,
  title text not null,
  slug text not null unique,
  content jsonb not null default '{}'::jsonb,
  order_index integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.syntax_examples (
  id bigint generated by default as identity primary key,
  language_id text not null references public.languages(id) on delete cascade,
  topic_id text not null references public.topics(id) on delete cascade,
  title text not null,
  code_example text not null,
  explanation text not null default '',
  output text not null default '',
  order_index integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.alternative_approaches (
  id bigint generated by default as identity primary key,
  language_id text not null references public.languages(id) on delete cascade,
  topic_id text not null references public.topics(id) on delete cascade,
  title text not null,
  idea text not null,
  code text not null,
  explanation text not null default '',
  time_complexity text not null default '',
  space_complexity text not null default '',
  advantages text[] not null default '{}'::text[],
  disadvantages text[] not null default '{}'::text[],
  when_to_use text not null default '',
  order_index integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.practice_questions (
  id bigint generated by default as identity primary key,
  language_id text not null references public.languages(id) on delete cascade,
  topic_id text not null references public.topics(id) on delete cascade,
  title text not null,
  prompt text not null,
  difficulty text not null default 'beginner',
  starter_code text not null default '',
  expected_output text not null default '',
  hints text[] not null default '{}'::text[],
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.test_cases (
  id bigint generated by default as identity primary key,
  practice_question_id bigint not null references public.practice_questions(id) on delete cascade,
  input text not null default '',
  expected_output text not null default '',
  is_hidden boolean not null default false,
  order_index integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text not null default '',
  level text not null default 'beginner',
  overview text not null default '',
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_languages (
  project_id bigint not null references public.projects(id) on delete cascade,
  language_id text not null references public.languages(id) on delete cascade,
  primary key (project_id, language_id)
);

create table if not exists public.learning_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  language_id text not null references public.languages(id) on delete cascade,
  topic_id text not null references public.topics(id) on delete cascade,
  status text not null default 'not_started',
  progress_percent integer not null default 0 check (progress_percent between 0 and 100),
  xp_earned integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, language_id, topic_id)
);

create table if not exists public.practice_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  practice_question_id bigint not null references public.practice_questions(id) on delete cascade,
  language_id text not null references public.languages(id) on delete cascade,
  submitted_code text not null default '',
  submitted_input text not null default '',
  submitted_output text not null default '',
  passed boolean not null default false,
  score numeric(5, 2) not null default 0,
  feedback jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.code_explanations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  language_id text not null references public.languages(id) on delete cascade,
  code_hash text not null,
  level text not null default 'beginner',
  prompt text not null default '',
  response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, language_id, code_hash, level)
);

create table if not exists public.chat_conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  human_language text not null default 'en',
  programming_language_id text not null references public.languages(id) on delete cascade,
  title text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.chat_conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_programs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  language_id text not null references public.languages(id) on delete cascade,
  title text not null,
  description text not null default '',
  active_version_number integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.program_versions (
  id bigint generated by default as identity primary key,
  saved_program_id bigint not null references public.saved_programs(id) on delete cascade,
  version_number integer not null,
  code text not null,
  input text not null default '',
  output text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (saved_program_id, version_number)
);

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  bookmark_type text not null,
  reference_id text not null,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, bookmark_type, reference_id)
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  language_id text not null references public.languages(id) on delete cascade,
  topic_id text not null references public.topics(id) on delete cascade,
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer text not null,
  explanation text not null default '',
  difficulty text not null default 'beginner',
  order_index integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  quiz_question_id bigint not null references public.quiz_questions(id) on delete cascade,
  selected_answer text not null,
  is_correct boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lessons_language_topic_idx on public.lessons (language_id, topic_id);
create index if not exists syntax_examples_language_topic_idx on public.syntax_examples (language_id, topic_id);
create index if not exists practice_questions_language_topic_idx on public.practice_questions (language_id, topic_id);
create index if not exists learning_progress_user_idx on public.learning_progress (user_id);
create index if not exists practice_attempts_user_idx on public.practice_attempts (user_id);
create index if not exists code_explanations_user_idx on public.code_explanations (user_id);
create index if not exists chat_conversations_user_idx on public.chat_conversations (user_id);
create index if not exists saved_programs_user_idx on public.saved_programs (user_id);
create index if not exists bookmarks_user_idx on public.bookmarks (user_id);
create index if not exists quiz_attempts_user_idx on public.quiz_attempts (user_id);

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_lessons'
  ) then
    create trigger set_updated_at_lessons
    before update on public.lessons
    for each row execute function public.set_updated_at();
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_topics'
  ) then
    create trigger set_updated_at_topics
    before update on public.topics
    for each row execute function public.set_updated_at();
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_profiles'
  ) then
    create trigger set_updated_at_profiles
    before update on public.profiles
    for each row execute function public.set_updated_at();
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'handle_new_user_profile'
  ) then
    create or replace function public.handle_new_user_profile()
    returns trigger
    language plpgsql
    security definer
    set search_path = public
    as $fn$
    begin
      insert into public.profiles (id, display_name)
      values (new.id, coalesce(new.raw_user_meta_data->>'display_name', ''))
      on conflict (id) do nothing;
      return new;
    end;
    $fn$;

    create trigger handle_new_user_profile
    after insert on auth.users
    for each row execute function public.handle_new_user_profile();
  end if;
end $$;

alter table public.languages enable row level security;
alter table public.profiles enable row level security;
alter table public.topics enable row level security;
alter table public.lessons enable row level security;
alter table public.syntax_examples enable row level security;
alter table public.alternative_approaches enable row level security;
alter table public.practice_questions enable row level security;
alter table public.test_cases enable row level security;
alter table public.projects enable row level security;
alter table public.project_languages enable row level security;
alter table public.learning_progress enable row level security;
alter table public.practice_attempts enable row level security;
alter table public.code_explanations enable row level security;
alter table public.chat_conversations enable row level security;
alter table public.chat_messages enable row level security;
alter table public.saved_programs enable row level security;
alter table public.program_versions enable row level security;
alter table public.bookmarks enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_attempts enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'languages' and policyname = 'Public read languages') then
    create policy "Public read languages"
      on public.languages
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'topics' and policyname = 'Public read topics') then
    create policy "Public read topics"
      on public.topics
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'lessons' and policyname = 'Public read lessons') then
    create policy "Public read lessons"
      on public.lessons
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'syntax_examples' and policyname = 'Public read syntax examples') then
    create policy "Public read syntax examples"
      on public.syntax_examples
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'alternative_approaches' and policyname = 'Public read alternative approaches') then
    create policy "Public read alternative approaches"
      on public.alternative_approaches
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'practice_questions' and policyname = 'Public read practice questions') then
    create policy "Public read practice questions"
      on public.practice_questions
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'projects' and policyname = 'Public read projects') then
    create policy "Public read projects"
      on public.projects
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'project_languages' and policyname = 'Public read project languages') then
    create policy "Public read project languages"
      on public.project_languages
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'quiz_questions' and policyname = 'Public read quiz questions') then
    create policy "Public read quiz questions"
      on public.quiz_questions
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'test_cases' and policyname = 'Authenticated read test cases') then
    create policy "Authenticated read test cases"
      on public.test_cases
      for select
      to authenticated
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users read own profile') then
    create policy "Users read own profile"
      on public.profiles
      for select
      to authenticated
      using (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users update own profile') then
    create policy "Users update own profile"
      on public.profiles
      for update
      to authenticated
      using (auth.uid() = id)
      with check (auth.uid() = id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'learning_progress' and policyname = 'Users manage own progress') then
    create policy "Users manage own progress"
      on public.learning_progress
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'practice_attempts' and policyname = 'Users manage own practice attempts') then
    create policy "Users manage own practice attempts"
      on public.practice_attempts
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'code_explanations' and policyname = 'Users manage own code explanations') then
    create policy "Users manage own code explanations"
      on public.code_explanations
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'chat_conversations' and policyname = 'Users manage own conversations') then
    create policy "Users manage own conversations"
      on public.chat_conversations
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'chat_messages' and policyname = 'Users manage own chat messages') then
    create policy "Users manage own chat messages"
      on public.chat_messages
      for all
      to authenticated
      using (
        exists (
          select 1
          from public.chat_conversations c
          where c.id = chat_messages.conversation_id
            and c.user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1
          from public.chat_conversations c
          where c.id = chat_messages.conversation_id
            and c.user_id = auth.uid()
        )
      );
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'saved_programs' and policyname = 'Users manage own saved programs') then
    create policy "Users manage own saved programs"
      on public.saved_programs
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'program_versions' and policyname = 'Users manage own program versions') then
    create policy "Users manage own program versions"
      on public.program_versions
      for all
      to authenticated
      using (
        exists (
          select 1
          from public.saved_programs s
          where s.id = program_versions.saved_program_id
            and s.user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1
          from public.saved_programs s
          where s.id = program_versions.saved_program_id
            and s.user_id = auth.uid()
        )
      );
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'bookmarks' and policyname = 'Users manage own bookmarks') then
    create policy "Users manage own bookmarks"
      on public.bookmarks
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'quiz_attempts' and policyname = 'Users manage own quiz attempts') then
    create policy "Users manage own quiz attempts"
      on public.quiz_attempts
      for all
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

insert into public.languages (
  id, display_name, file_extension, comment_syntax, execution_runtime, compiled, tier, sort_order, supports_stdin, supports_packages
)
values
  ('python', 'Python', '.py', '#', 'python-3.11', false, 1, 1, true, true),
  ('c', 'C', '.c', '//', 'gcc-13', true, 1, 2, true, false),
  ('cpp', 'C++', '.cpp', '//', 'g++-13', true, 1, 3, true, true),
  ('java', 'Java', '.java', '//', 'openjdk-21', true, 1, 4, true, true),
  ('javascript', 'JavaScript', '.js', '//', 'node-22', false, 1, 5, true, true),
  ('sql', 'SQL', '.sql', '--', 'postgres-16', false, 1, 6, false, false)
on conflict (id) do update set
  display_name = excluded.display_name,
  file_extension = excluded.file_extension,
  comment_syntax = excluded.comment_syntax,
  execution_runtime = excluded.execution_runtime,
  compiled = excluded.compiled,
  tier = excluded.tier,
  sort_order = excluded.sort_order,
  supports_stdin = excluded.supports_stdin,
  supports_packages = excluded.supports_packages;
